# Generated by Django 2.1.1 on 2018-11-21 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('num_manilla', models.IntegerField(primary_key=True, serialize=False)),
                ('codigo', models.IntegerField(unique=True)),
                ('cedula', models.IntegerField(unique=True)),
                ('nombre', models.CharField(max_length=50)),
                ('programa', models.CharField(max_length=50)),
                ('tel_familiar', models.CharField(max_length=10)),
                ('familiar', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=10)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='')),
                ('observacion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingreso', models.DateField()),
                ('salida', models.DateField()),
                ('observacion', models.TextField()),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.Estudiante')),
            ],
        ),
    ]
